### ISSUE TITLE
Basic example not working

### ISSUE THREAD

**Issue by IgnisDa** [Epistates/turbomcp#1]
Thanks for this project! I was having a problem setting up a project using turbomcp. I was able to fix the issues but I wanted to make you aware of the issues.

I have the following in `main.rs`:

```rs
use turbomcp::prelude::*;

#[derive(Clone)]
struct LocalLoreServer;

#[server(name = "local-lore", version = "0.1.0")]
impl LocalLoreServer {
    #[tool("Say hello to someone")]
    async fn hello(&self, name: String) -> McpResult<String> {
        Ok(format!("Hello, {name}! Welcome to Local Lore."))
    }

    #[tool("Get information about the current directory")]
    async fn get_current_directory(&self) -> McpResult<String> {
        let current_dir = std::env::current_dir()
            .map_err(|e| McpError::internal(format!("Failed to get current directory: {}", e)))?;

        Ok(format!("Current directory: {}", current_dir.display()))
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    LocalLoreServer.run_stdio().await?;
    Ok(())
}
```

and this in my `Cargo.toml`:

```toml
[package]
name = "local-lore"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "=1.0.145"
turbomcp = "=2.0.2"
tokio = { version = "=1.48.0", features = ["full"] }
```

Here is the error I am getting:

```
   Compiling local-lore v0.1.0 (/Users/diptesh/Desktop/Code/local-lore)
error[E0433]: failed to resolve: use of unresolved module or unlinked crate `turbomcp_protocol`
 --> src/main.rs:6:1
  |
6 | #[server(name = "local-lore", version = "0.1.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `turbomcp_protocol`
  |
  = help: if you wanted to use a crate named `turbomcp_protocol`, use `cargo add turbomcp_protocol` to add it to your `Cargo.toml`
  = note: this error originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of unresolved module or unlinked crate `turbomcp_server`
 --> src/main.rs:6:1
  |
6 | #[server(name = "local-lore", version = "0.1.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `turbomcp_server`
  |
  = help: if you wanted to use a crate named `turbomcp_server`, use `cargo add turbomcp_server` to add it to your `Cargo.toml`
  = note: this error originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of unresolved module or unlinked crate `turbomcp_protocol`
 --> src/main.rs:6:1
  |
6 | #[server(name = "local-lore", version = "0.1.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `turbomcp_protocol`
  |
  = help: if you wanted to use a crate named `turbomcp_protocol`, use `cargo add turbomcp_protocol` to add it to your `Cargo.toml`
  = note: this error originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this crate
  |
1 + use turbomcp::turbomcp_protocol;
  |

error[E0433]: failed to resolve: use of unresolved module or unlinked crate `turbomcp_protocol`
 --> src/main.rs:6:1
  |
6 | #[server(name = "local-lore", version = "0.1.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `turbomcp_protocol`
  |
  = help: if you wanted to use a crate named `turbomcp_protocol`, use `cargo add turbomcp_protocol` to add it to your `Cargo.toml`
  = note: this error originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
  |
1 + use turbomcp::RequestContext;
  |

warning: unexpected `cfg` condition value: `http`
 --> src/main.rs:6:1
  |
6 | #[server(name = "local-lore", version = "0.1.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: no expected values for `feature`
  = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
  = help: try referring to `server` crate for guidance on how handle this unexpected cfg
  = help: the attribute macro `server` may come from an old version of the `turbomcp_macros` crate, try updating your dependency with `cargo update -p turbomcp_macros`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default
  = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `websocket`
 --> src/main.rs:6:1
  |
6 | #[server(name = "local-lore", version = "0.1.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: no expected values for `feature`
  = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
  = help: try referring to `server` crate for guidance on how handle this unexpected cfg
  = help: the attribute macro `server` may come from an old version of the `turbomcp_macros` crate, try updating your dependency with `cargo update -p turbomcp_macros`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `tcp`
 --> src/main.rs:6:1
  |
6 | #[server(name = "local-lore", version = "0.1.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: no expected values for `feature`
  = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
  = help: try referring to `server` crate for guidance on how handle this unexpected cfg
  = help: the attribute macro `server` may come from an old version of the `turbomcp_macros` crate, try updating your dependency with `cargo update -p turbomcp_macros`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `unix`
 --> src/main.rs:6:1
  |
6 | #[server(name = "local-lore", version = "0.1.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: no expected values for `feature`
  = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
  = help: try referring to `server` crate for guidance on how handle this unexpected cfg
  = help: the attribute macro `server` may come from an old version of the `turbomcp_macros` crate, try updating your dependency with `cargo update -p turbomcp_macros`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0433`.
warning: `local-lore` (bin "local-lore") generated 4 warnings
error: could not compile `local-lore` (bin "local-lore") due to 4 previous errors; 4 warnings emitted
```

It gets fixed if i add this to `Cargo.toml`:

```toml
turbomcp-protocol = "=2.0.2"
turbomcp-server = "=2.0.2"
```

I still have warnings that I am unable to resolve:

```
   Compiling local-lore v0.1.0 (/Users/diptesh/Desktop/Code/local-lore)
warning: unexpected `cfg` condition value: `http`
 --> src/main.rs:6:1
  |
6 | #[server(name = "local-lore", version = "0.1.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: no expected values for `feature`
  = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
  = help: try referring to `server` crate for guidance on how handle this unexpected cfg
  = help: the attribute macro `server` may come from an old version of the `turbomcp_macros` crate, try updating your dependency with `cargo update -p turbomcp_macros`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default
  = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `websocket`
 --> src/main.rs:6:1
  |
6 | #[server(name = "local-lore", version = "0.1.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: no expected values for `feature`
  = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
  = help: try referring to `server` crate for guidance on how handle this unexpected cfg
  = help: the attribute macro `server` may come from an old version of the `turbomcp_macros` crate, try updating your dependency with `cargo update -p turbomcp_macros`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `tcp`
 --> src/main.rs:6:1
  |
6 | #[server(name = "local-lore", version = "0.1.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: no expected values for `feature`
  = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
  = help: try referring to `server` crate for guidance on how handle this unexpected cfg
  = help: the attribute macro `server` may come from an old version of the `turbomcp_macros` crate, try updating your dependency with `cargo update -p turbomcp_macros`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `unix`
 --> src/main.rs:6:1
  |
6 | #[server(name = "local-lore", version = "0.1.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: no expected values for `feature`
  = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
  = help: try referring to `server` crate for guidance on how handle this unexpected cfg
  = help: the attribute macro `server` may come from an old version of the `turbomcp_macros` crate, try updating your dependency with `cargo update -p turbomcp_macros`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `local-lore` (bin "local-lore") generated 4 warnings
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.15s
     Running `target/debug/local-lore`
```

Please let me know if I can provide other information. Thank you for this project!

**Comment by nicholasjpaterno** [comment]
Resolved by [46a555b](https://github.com/Epistates/turbomcp/commit/46a555b9244b5874025ed05747d4841296f718a8)

**Comment by IgnisDa** [comment]
Hey @nicholasjpaterno, thanks for addressing the issue. I can confirm it works as expected now. I am still getting these warnings:

```
warning: unexpected `cfg` condition value: `http`
  --> src/main.rs:38:1
   |
38 | #[server(name = "Local Lore", version = "0.1.0")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: no expected values for `feature`
   = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
   = help: try referring to `server` crate for guidance on how handle this unexpected cfg
   = help: the attribute macro `server` may come from an old version of the `turbomcp_macros` crate, try updating your dependency with `cargo update -p turbomcp_macros`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
   = note: `#[warn(unexpected_cfgs)]` on by default
   = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `websocket`
  --> src/main.rs:38:1
   |
38 | #[server(name = "Local Lore", version = "0.1.0")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: no expected values for `feature`
   = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
   = help: try referring to `server` crate for guidance on how handle this unexpected cfg
   = help: the attribute macro `server` may come from an old version of the `turbomcp_macros` crate, try updating your dependency with `cargo update -p turbomcp_macros`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
   = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `tcp`
  --> src/main.rs:38:1
   |
38 | #[server(name = "Local Lore", version = "0.1.0")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: no expected values for `feature`
   = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
   = help: try referring to `server` crate for guidance on how handle this unexpected cfg
   = help: the attribute macro `server` may come from an old version of the `turbomcp_macros` crate, try updating your dependency with `cargo update -p turbomcp_macros`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
   = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `unix`
  --> src/main.rs:38:1
   |
38 | #[server(name = "Local Lore", version = "0.1.0")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: no expected values for `feature`
   = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
   = help: try referring to `server` crate for guidance on how handle this unexpected cfg
   = help: the attribute macro `server` may come from an old version of the `turbomcp_macros` crate, try updating your dependency with `cargo update -p turbomcp_macros`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
   = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Any suggestions on what I can do to make them go away?

**Comment by IgnisDa** [comment]
Also in case you missed it, the docs fail to build: 

<img width="923" height="175" alt="Image" src="https://github.com/user-attachments/assets/fb47f1b4-37a8-424f-8790-e608cb634c78" />

(https://docs.rs/crate/turbomcp/latest)

**Comment by nicholasjpaterno** [comment]
Ok, for right now, I would suggest going to your cargo.toml and selecting just the transport you want to use, in the case of your example:
```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    LocalLoreServer.run_stdio().await?; // <------ You're running stdio so we want to change your cargo.toml 
    Ok(())
}
```
If you dont need the other transports you can use the `minimal` or `default` feature group https://github.com/Epistates/turbomcp/blob/main/crates/turbomcp/Cargo.toml#L167-L172. Right now theres a bit of magic where the macro generates code for all the transports (http, websocket, tcp, etc) that you have enabled in your cargo.toml
```toml
turbomcp = { version = "=2.0.3", features = ["default"] }
```

In 1.0.4 i'll ship a way to explicitly narrow that despite the transports you have enabled on the library. This would enable. for example, you could have multiple servers in the same binary:
```rust
// ✅ Explicit - narrow to local transport
  #[server(name = "local-lore", version = "0.1.0", transports = ["stdio"])]
  impl LocalLoreServer { }

// ✅ Explicit - narrow to specific transports
  #[server(name = "http-lore", version = "0.1.0", transports = ["http"])]
  impl HttpLoreServer { } 

// Same binary, multiple servers, different purposes
  #[tokio::main]
  async fn main() {
      // Public REST API over HTTP only
      tokio::spawn(HttpLoreServer::run_http("0.0.0.0:8080"));

      // Internal RPC over STDIO only
      tokio::spawn(LocalLoreServer::run_stdio());
  }
```

**Comment by nicholasjpaterno** [comment]
Reopening this issue for now to track this.

**Comment by nicholasjpaterno** [comment]
Are you running a nightly build of rust per chance? I'll be shipping 1.0.4 soon that will address this issue but it seems to only show the warnings for nightly users. In any case, it will be a change exactly like this:
```rust
// ✅ Explicit - narrow to local transport
  #[server(name = "local-lore", version = "0.1.0", transports = ["stdio"])]
  impl LocalLoreServer { } // ---------------------^^^^^^^^^^^^^^^^^^^^
```
Which will narrow the macro code generated to just the transports you want per server.

**Comment by IgnisDa** [comment]
what if i want to enable more than one transports?

**Comment by nicholasjpaterno** [comment]
You should be able to do both:
```rust
// ✅ Explicit - narrow to local transport
  #[server(name = "local-lore", version = "0.1.0", transports = ["stdio"])]
  impl LocalLoreServer { }

// ✅ Different server purpose and different transport
  #[server(name = "http-different", version = "0.1.0", transports = ["http"])]
  impl HttpLoreServer { } 

// Same binary, multiple servers, different purposes
  #[tokio::main]
  async fn main() {
      // Public REST API over HTTP only
      tokio::spawn(HttpLoreServer::run_http("0.0.0.0:8080"));

      // Internal RPC over STDIO only
      tokio::spawn(LocalLoreServer::run_stdio());
  }
```
OR:
```rust
// ✅ Explicit - narrow to local transport
  #[server(name = "local-lore", version = "0.1.0", transports = ["stdio", "http"])]
  impl LoreServer { }

// Same binary, multiple servers, different purposes
  #[tokio::main]
  async fn main() {
      // Public REST API over HTTP only
      tokio::spawn(LoreServer::run_http("0.0.0.0:8080"));

      // Internal RPC over STDIO only
      tokio::spawn(LoreServer::run_stdio());
  }
```

**Comment by nicholasjpaterno** [comment]
It will be in `1.0.4` which should ship in the next 30mins if the CI passes!

**Comment by IgnisDa** [comment]
Thank you very much! It works as expected.
